# @author hanchao <hanchao@66yunlian.com>
# @since 0.1.0

user nginx;
worker_processes auto;
pid /run/nginx-uix/nginx.pid;
error_log stderr warn;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout combined;
    include conf.d/*.conf;
}
