# @author hanchao <hanchao@66yunlian.com>
# @since 0.1.0

server {
    listen 80 default_server;
    server_name _;

    root html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
